### ISSUE TITLE
Struggling to install

### ISSUE THREAD

**Issue by pricecurrent** [hyrious/prettierd#2]
Hey @hyrious 

Thank you for putting it together. I seem to struggle with installing it though.

Do I need to have https://github.com/jonlabelle/SublimeJsPrettier plugin installed for yours one to work? 

I followed everything from the readme, I have node and prettier available globally. I added repo to sublime text. I tried with JsPrettier plugin installed and without it. With JsPrettier it still uses JsPrettier to prettify, without it, it doesn't do anything.

Further more `CMD + Shift + P, Preferences: Prettier` isn't available for me, i.e. there is not "preferences: Prettier command.

Any help would be highly appreciated getting it up and running.

I consider donating you if this thing will really work and my prettifying will go down from 500ms I will be the most happy person on earth.

**Comment by hyrious** [comment]
Hi! Thank you for giving it a try.

You don't have to install JsPrettier to use this plugin.

The readme has an oversight that `Package Control: Add Repository` does not actually install the package, you still have to `Package Control: Install Package` to bring it to your disk. I just fixed that in the doc and have verified that it works on my Windows (will further test that on macOS some days after).

I've also included some other installation methods in the readme. If you're struggling in one, you can try another. Some advices:

1. Open the sublime text console via <kbd>ctrl+\`</kbd> to check any error message.
2. Restart the editor once installed.

**Comment by pricecurrent** [comment]
HUGE Thank you!

It's blazing fast! 

Can I donate you?

**Comment by hyrious** [comment]
Glad to hear it works for you.

There's no need to donate, I make tools because I need them too and I want to share them to others freely.

**Comment by pricecurrent** [comment]
Thank you so much sir
